# Generated by Django 3.1.4 on 2024-04-24 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_leadstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadstatus',
            options={'verbose_name_plural': 'LeadStatuses'},
        ),
    ]
