# Generated by Django 3.1.4 on 2024-04-24 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20240423_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadstatus',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
        ),
    ]
