# Generated by Django 3.1.4 on 2024-04-24 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_leadstatus_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadstatus',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
        ),
    ]
